import Link from "next/link";

const S = {
  bg:          "#0f0f0e",
  surface:     "#1a1a18",
  border:      "#2e2e2b",
  white:       "#f5f0e8",
  muted:       "#7a7a6e",
  mutedLight:  "#a0a090",
  muscle:      "#c8f04a",
};

export const metadata = {
  title: "Terms of Service — CaliPlan",
  description: "The terms that apply when you use CaliPlan.",
};

export default function TermsPage() {
  return (
    <main style={{ minHeight: "100dvh", background: S.bg, padding: "3.5rem 1.25rem 4rem" }}>
      <article style={{ maxWidth: "680px", margin: "0 auto", color: S.mutedLight, lineHeight: 1.7, fontSize: "0.95rem" }}>

        <Link href="/" style={{ display: "inline-block", marginBottom: "2rem", fontSize: "0.8rem", color: S.muted, textDecoration: "none" }}>
          ← Back home
        </Link>

        <p style={{ margin: "0 0 0.5rem", fontSize: "0.72rem", letterSpacing: "0.1em", textTransform: "uppercase", color: S.muted }}>
          Legal
        </p>
        <h1 className="font-display" style={{ margin: "0 0 0.5rem", fontSize: "2.25rem", fontWeight: 800, color: S.white, letterSpacing: "-0.03em", lineHeight: 1.1 }}>
          Terms of Service
        </h1>
        <p style={{ margin: "0 0 2rem", fontSize: "0.8rem", color: S.muted }}>
          Last updated: April 10, 2026
        </p>

        <p style={{ margin: "0 0 2rem" }}>
          Welcome to CaliPlan. By using the app, you agree to these terms. We&apos;ve kept them as short and plain as we can.
        </p>

        <h2 style={H2}>What CaliPlan is</h2>
        <p style={P}>
          CaliPlan is a calisthenics training app that creates personalized weekly workout plans based on your current strength and goals. Free users can complete a one-time assessment and receive a 1-week plan. Pro subscribers get adaptive weekly plans that update based on logged workouts, full skill tree progression tracking, and ongoing access to all training tools.
        </p>
        <p style={P}>
          CaliPlan is operated by <strong style={{ color: S.white }}>Manly Prime</strong>, based in Denmark.
        </p>

        <h2 style={H2}>Who can use CaliPlan</h2>
        <p style={P}>
          You must be at least 16 years old to use CaliPlan. By creating an account, you confirm that you are.
        </p>

        <h2 style={H2}>Your account</h2>
        <p style={P}>
          You are responsible for keeping your account credentials safe. Don&apos;t share your account with others. If you suspect someone else has accessed your account, email us right away.
        </p>

        <h2 style={H2}>Subscription and billing</h2>
        <p style={P}>
          Pro subscriptions are billed monthly or yearly through Stripe. Subscriptions auto-renew at the end of each billing period unless you cancel.
        </p>
        <p style={P}>
          By subscribing, you authorize us (via Stripe) to charge your selected payment method on each renewal.
        </p>

        <h2 style={H2}>Cancellation</h2>
        <p style={P}>
          You can cancel your subscription at any time from the <strong style={{ color: S.white }}>Settings</strong> page in the app. Click <strong style={{ color: S.white }}>Manage subscription</strong> to open your Stripe billing portal, then choose to cancel.
        </p>
        <p style={P}>
          Cancellation takes effect at the end of your current billing period. You keep pro access until that date — we don&apos;t end access mid-period.
        </p>

        <h2 style={H2}>Refunds</h2>
        <p style={P}>
          We handle refunds on a case-by-case basis. If you have a billing concern, email us at <a href="mailto:fillipdavidsen@gmail.com" style={A}>fillipdavidsen@gmail.com</a> and we&apos;ll work with you in good faith.
        </p>

        <h2 style={H2}>Not medical advice</h2>
        <p style={P}>
          CaliPlan is a fitness tool, not a medical service. Workout plans generated by the app are based on the information you provide and are intended as general guidance. They are not a substitute for advice from a doctor, physiotherapist, or qualified coach.
        </p>
        <p style={P}>
          Before starting any new exercise program, we recommend consulting a healthcare professional, especially if you have any pre-existing conditions or injuries.
        </p>
        <p style={P}>
          You exercise at your own risk. CaliPlan is not responsible for injuries or health issues that result from following plans generated by the app.
        </p>

        <h2 style={H2}>Acceptable use</h2>
        <p style={P}>When using CaliPlan, you agree not to:</p>
        <ul style={UL}>
          <li>Share your account with others or attempt to bypass subscription requirements</li>
          <li>Reverse engineer, scrape, or extract our content for commercial use</li>
          <li>Use the app to harm others or violate applicable laws</li>
          <li>Interfere with or disrupt the service</li>
        </ul>

        <h2 style={H2}>Service availability and changes</h2>
        <p style={P}>
          We work to keep CaliPlan available and reliable, but we don&apos;t guarantee uninterrupted access. We may update, change, or discontinue features at any time. If we make a major change that affects your subscription, we&apos;ll let you know.
        </p>

        <h2 style={H2}>Limitation of liability</h2>
        <p style={P}>
          To the maximum extent permitted by law, CaliPlan and Manly Prime are not liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability for any claim is limited to the amount you paid for your subscription in the 12 months prior to the claim.
        </p>

        <h2 style={H2}>Governing law</h2>
        <p style={P}>
          These terms are governed by the laws of Denmark.
        </p>

        <h2 style={H2}>Changes to these terms</h2>
        <p style={P}>
          We may update these terms from time to time. If we make material changes, we&apos;ll update the &ldquo;Last updated&rdquo; date at the top and notify you through the app or by email.
        </p>

        <h2 style={H2}>Contact</h2>
        <p style={P}>
          Questions about these terms: <a href="mailto:fillipdavidsen@gmail.com" style={A}>fillipdavidsen@gmail.com</a>
        </p>

        <div style={{ marginTop: "3rem", paddingTop: "1.5rem", borderTop: `1px solid ${S.border}`, display: "flex", gap: "1.5rem", fontSize: "0.8rem" }}>
          <Link href="/privacy" style={{ color: S.muted, textDecoration: "none" }}>Privacy</Link>
          <Link href="/contact" style={{ color: S.muted, textDecoration: "none" }}>Contact</Link>
          <Link href="/" style={{ color: S.muted, textDecoration: "none" }}>Home</Link>
        </div>
      </article>
    </main>
  );
}

const H2: React.CSSProperties = {
  margin: "2rem 0 0.75rem",
  fontSize: "1.15rem",
  fontWeight: 700,
  color: S.white,
  letterSpacing: "-0.01em",
};

const P: React.CSSProperties = {
  margin: "0 0 1rem",
};

const UL: React.CSSProperties = {
  margin: "0 0 1.25rem 1.25rem",
  padding: 0,
};

const A: React.CSSProperties = {
  color: S.muscle,
  textDecoration: "none",
  borderBottom: `1px solid ${S.muscle}`,
};
